services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: crud_postgres
    environment:
      POSTGRES_DB: crudapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crudapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Node.js Backend Application
  backend:
    build: .
    container_name: crud_backend
    environment:
      DATABASE_URL: postgresql://postgres:password123@db:5432/crudapp
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/healthz', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
